node {
    def mvnHome

    stage('Preparation') {
        git([url: 'https://github.com/anoopsimon/java-endtoend-fw.git', branch: 'main'])
        mvnHome = tool 'M3'
    }

    stage('Build') {
        sh "'${mvnHome}/bin/mvn' clean package -DskipTests=true"
    }

    stage('Test Execution') {
        try {
         sh "'${mvnHome}/bin/mvn' -pl core clean install exec:java -Dexec.classpathScope=test"

        } catch (Exception e) {
            currentBuild.result = 'FAILURE'
        } finally {
            junit '**/target/surefire-reports/TEST-*.xml'

            /*
             * Please read https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy
             * to allow Jenkins to load static files
             */
            publishHTML (target: [
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'core/target/surefire-reports',
                reportFiles: 'index.html',
                reportName: "Test Report"
            ])
        }
    }
}