node {
    def mvnHome

    stage('Preparation') {
        git([url: 'https://github.com/anoopsimon/java-endtoend-fw.git', branch: 'main'])

        mvnHome = tool 'M3'
    }

    stage('Build') {
        sh "cd core"
        sh "'${mvnHome}/bin/mvn' clean package -DskipTests=true"
    }

    stage('Test Execution') {
        try {
           // sh "'${mvnHome}/bin/mvn' test -Pweb-execution -Dtarget=local -Dsuite=local -Dtestng.dtd.http=true"
         sh "cd core"
         sh "'${mvnHome}/bin/mvn' clean install exec:java -Dexec.classpathScope=test -Dexec.args='-tags @demo' -Denvironment=uat"

        } catch (Exception e) {
            currentBuild.result = 'FAILURE'
        } finally {
            junit '**/target/surefire-reports/TEST-*.xml'

            /*
             * Please read https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy
             * to allow Jenkins to load static files
             */
            publishHTML (target: [
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'target/surefire-reports',
                reportFiles: 'index.html',
                reportName: "TestNG Report"
            ])
        }
    }
}